controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0

    global_frame: "map"
    odom_frame: "odom"
    robot_base_frame: "base_link"
    cmd_vel_topic: "cmd_vel"

    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]

    controller_plugins: ["FollowPathMPPI"] #erdetileg RPP-t használtam, de nem volt megbízható a működése

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 10.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.3 #0.05
      yaw_goal_tolerance: 0.3 #0.1
      stateful: true

    FollowPathMPPI:
      plugin: "nav2_mppi_controller::MPPIController"
      motion_model: "DiffDrive"

      # Stabil indulás 10 Hz-hez
      model_dt: 0.1
      time_steps: 25
      batch_size: 2000
      iteration_count: 1

      # Sebességek
      vx_max: 0.35
      vx_min: 0.00
      wz_max: 1.8
      vy_max: 0.0

      # Ne legyen túl "szétszórt" (különben sokat forog)
      vx_std: 0.12
      wz_std: 0.35

      prune_distance: 1.5

      #KRITIKÁK: ettől lesz "jó irány + tempó"
      critics: [
        "ConstraintCritic",
        "CostCritic",
        "PathAlignCritic",
        "PathFollowCritic",
        "GoalCritic",
        "GoalAngleCritic",
        "PreferForwardCritic"
      ]

      PreferForwardCritic:
        enabled: true
        weight: 2.0

      PathFollowCritic:
        enabled: true
        weight: 5.0

      PathAlignCritic:
        enabled: true
        weight: 4.0

      GoalCritic:
        enabled: true
        weight: 2.0

      GoalAngleCritic:
        enabled: true
        weight: 4.0

      CostCritic:
        enabled: true
        weight: 2.0




#  LOCAL COSTMAP
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true

      global_frame: "map"
      robot_base_frame: "base_link"

      update_frequency: 10.0
      publish_frequency: 10.0

      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05 #0.1

      # egyszerű téglalap footprint
      #footprint: "[[0.25, 0.15], [0.25, -0.15], [-0.25, -0.15], [-0.25, 0.15]]"
      #footprint: "[[0.25, 0.18], [0.25, -0.18], [-0.25, -0.18], [-0.25, 0.18]]"
      footprint: "[[0.25, 0.20], [0.25, -0.20], [-0.25, -0.20], [-0.25, 0.20]]"
      footprint_padding: 0.03 #0.02

      # FONTOS: a te /map occupancy gridedet is vegye át
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
        map_subscribe_transient_local: true
        map_topic: "/map"

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: "scan"
        scan:
          topic: "lidar"          # a 2D lidar ROS topic neve
          clearing: true
          marking: true
          data_type: "LaserScan"
          obstacle_range: 5.0
          raytrace_range: 6.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.30 #0.5
        cost_scaling_factor: 5.0 #3.0

